import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./_component/Provider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider viewport={cookieStore.get('viewport')?.value === 'mobile' ? 'mobile' : 'desktop'}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
